-- =============================================
-- SUFashion - cart_items table
-- Supabase Project: eatekbcknwqxfunyuwel
-- Schema source: Supabase OpenAPI (service role)
-- NOT NULL: id, product_id
-- Supports both guest (session_id) and logged-in (user_id) users
-- =============================================

CREATE TABLE IF NOT EXISTS public.cart_items (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    quantity   INTEGER NOT NULL DEFAULT 1,
    session_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;

-- Users can view own cart by user_id, guests by session_id
CREATE POLICY "Users can view own cart items"
    ON public.cart_items
    FOR SELECT
    USING (auth.uid() = user_id);

-- Anyone can insert (guest or logged-in)
CREATE POLICY "Anyone can add to cart"
    ON public.cart_items
    FOR INSERT
    WITH CHECK (true);

-- Users can delete their own cart items
CREATE POLICY "Users can delete own cart items"
    ON public.cart_items
    FOR DELETE
    USING (auth.uid() = user_id);

-- Service role full access
CREATE POLICY "Service role can manage cart items"
    ON public.cart_items
    FOR ALL
    USING (true)
    WITH CHECK (true);
