-- =============================================
-- SUFashion - credit_cards table
-- Supabase Project: eatekbcknwqxfunyuwel
-- Sensitive card token stored encrypted via pgcrypto (pgp_sym_encrypt)
-- NOT NULL: id, user_id, last4, brand, exp_month, exp_year
-- =============================================

-- Enable pgcrypto extension (run once per project)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.credit_cards (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id               UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

    -- Visible (non-sensitive) card metadata
    last4                 CHAR(4)     NOT NULL,
    brand                 TEXT        NOT NULL,   -- 'Visa', 'Mastercard', 'Amex', etc.
    exp_month             SMALLINT    NOT NULL CHECK (exp_month BETWEEN 1 AND 12),
    exp_year              SMALLINT    NOT NULL CHECK (exp_year >= 2024),

    -- Encrypted sensitive data:
    -- Store via: pgp_sym_encrypt('token_value', current_setting('app.encryption_key'))
    -- Read via:  pgp_sym_decrypt(card_token_encrypted, current_setting('app.encryption_key'))
    card_token_encrypted  BYTEA,

    is_default            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Only one default card per user
CREATE UNIQUE INDEX IF NOT EXISTS unique_default_card_per_user
    ON public.credit_cards (user_id)
    WHERE is_default = TRUE;

-- Enable Row Level Security
ALTER TABLE public.credit_cards ENABLE ROW LEVEL SECURITY;

-- Users can only see their own cards
CREATE POLICY "Users can view own cards"
    ON public.credit_cards
    FOR SELECT
    USING (auth.uid() = user_id);

-- Users can insert their own cards
CREATE POLICY "Users can add own cards"
    ON public.credit_cards
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Users can update their own cards (e.g. set default)
CREATE POLICY "Users can update own cards"
    ON public.credit_cards
    FOR UPDATE
    USING (auth.uid() = user_id);

-- Users can delete their own cards
CREATE POLICY "Users can delete own cards"
    ON public.credit_cards
    FOR DELETE
    USING (auth.uid() = user_id);

-- Service role full access
CREATE POLICY "Service role can manage cards"
    ON public.credit_cards
    FOR ALL
    USING (true)
    WITH CHECK (true);
