-- =============================================
-- SUFashion - invoices table
-- Supabase Project: eatekbcknwqxfunyuwel
-- NOT NULL: id, order_id, user_id, invoice_number, subtotal, tax_amount, total_amount
-- =============================================

CREATE TABLE IF NOT EXISTS public.invoices (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT          NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id          UUID            NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    invoice_number   TEXT            NOT NULL UNIQUE,
    subtotal         NUMERIC(12, 2)  NOT NULL DEFAULT 0,
    tax_amount       NUMERIC(12, 2)  NOT NULL DEFAULT 0,
    total_amount     NUMERIC(12, 2)  NOT NULL DEFAULT 0,
    status           TEXT            NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'paid', 'cancelled')),
    pdf_url          TEXT,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Auto-generate invoice number: INV-YYYYMMDD-XXXXX
CREATE OR REPLACE FUNCTION public.generate_invoice_number()
RETURNS TRIGGER AS $$
BEGIN
    NEW.invoice_number := 'INV-'
        || TO_CHAR(NOW(), 'YYYYMMDD')
        || '-'
        || LPAD(NEW.id::TEXT, 5, '0');
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER set_invoice_number
    BEFORE INSERT ON public.invoices
    FOR EACH ROW
    WHEN (NEW.invoice_number IS NULL OR NEW.invoice_number = '')
    EXECUTE FUNCTION public.generate_invoice_number();

-- Enable Row Level Security
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;

-- Users can view their own invoices
CREATE POLICY "Users can view own invoices"
    ON public.invoices
    FOR SELECT
    USING (auth.uid() = user_id);

-- Service role full access
CREATE POLICY "Service role can manage invoices"
    ON public.invoices
    FOR ALL
    USING (true)
    WITH CHECK (true);
