-- =============================================
-- SUFashion - orders table
-- Supabase Project: eatekbcknwqxfunyuwel
-- Schema source: Supabase OpenAPI (service role) + checkout update
-- NOT NULL: id, user_id, product_id, quantity, total_price
-- =============================================

-- ── Core table ────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.orders (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          UUID            NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id       BIGINT          NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    quantity         INTEGER         NOT NULL,
    total_price      NUMERIC(12, 2)  NOT NULL,

    -- Checkout fields
    status           TEXT            NOT NULL DEFAULT 'processing'
                        CHECK (status IN ('processing', 'shipped', 'delivered', 'cancelled')),
    shipping_address TEXT,
    payment_method   TEXT            DEFAULT 'card'
                        CHECK (payment_method IN ('card', 'store_credit', 'cash_on_delivery')),
    invoice_id           BIGINT          REFERENCES public.invoices(id) ON DELETE SET NULL,

    -- Cancellation tracking (Req 12)
    cancelled_at         TIMESTAMPTZ,
    cancellation_reason  TEXT,

    created_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ── If the table already exists, add new columns safely ───────────────────────

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS status           TEXT NOT NULL DEFAULT 'processing'
        CHECK (status IN ('processing', 'shipped', 'delivered', 'cancelled'));

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS shipping_address TEXT;

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS payment_method   TEXT DEFAULT 'card'
        CHECK (payment_method IN ('card', 'store_credit', 'cash_on_delivery'));

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS invoice_id       BIGINT REFERENCES public.invoices(id) ON DELETE SET NULL;

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS cancelled_at        TIMESTAMPTZ;

ALTER TABLE public.orders
    ADD COLUMN IF NOT EXISTS cancellation_reason TEXT;

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Users can view their own orders
CREATE POLICY "Users can view own orders"
    ON public.orders
    FOR SELECT
    USING (auth.uid() = user_id);

-- Service role full access (creates orders, updates stock, links invoices)
CREATE POLICY "Service role can manage orders"
    ON public.orders
    FOR ALL
    USING (true)
    WITH CHECK (true);
