-- =============================================
-- SUFashion - products table
-- Supabase Project: eatekbcknwqxfunyuwel
-- Schema source: Supabase OpenAPI (service role)
-- NOT NULL: id, name, price
-- =============================================

CREATE TABLE IF NOT EXISTS public.products (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT NOT NULL,
    category         TEXT,
    description      TEXT,
    price            NUMERIC NOT NULL,
    image_url        TEXT,
    quantity         INTEGER NOT NULL DEFAULT 0,
    is_limited       BOOLEAN NOT NULL DEFAULT FALSE,
    old_price        NUMERIC,
    model            TEXT,
    serial_number    TEXT,
    warranty_status  TEXT,
    distributor_info TEXT,
    popularity       INTEGER NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- Public read access
CREATE POLICY "Products are viewable by everyone"
    ON public.products
    FOR SELECT
    USING (true);

-- Service role full access
CREATE POLICY "Service role can manage products"
    ON public.products
    FOR ALL
    USING (true)
    WITH CHECK (true);
