-- =============================================
-- SUFashion - refunds table (Req 11)
-- Post-delivery return/refund requests
-- Supabase Project: eatekbcknwqxfunyuwel
-- =============================================

CREATE TABLE IF NOT EXISTS public.refunds (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT          NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
    user_id      UUID            NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    amount       NUMERIC(12, 2)  NOT NULL,
    reason       TEXT,
    status       TEXT            NOT NULL DEFAULT 'pending'
                   CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    resolved_at  TIMESTAMPTZ
);

-- ── Trigger: approve → restore stock + set resolved_at ───────────────────────

CREATE OR REPLACE FUNCTION public.handle_refund_status_change()
RETURNS TRIGGER AS $$
DECLARE
    v_product_id BIGINT;
    v_quantity   INTEGER;
BEGIN
    IF NEW.status <> OLD.status AND NEW.status IN ('approved', 'rejected') THEN
        NEW.resolved_at := NOW();
    END IF;

    IF NEW.status = 'approved' AND OLD.status <> 'approved' THEN
        SELECT product_id, quantity
          INTO v_product_id, v_quantity
          FROM public.orders
         WHERE id = NEW.order_id;

        -- Restore stock
        UPDATE public.products
           SET quantity = quantity + v_quantity,
               returns  = returns  + v_quantity
         WHERE id = v_product_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_refund_status_change
    BEFORE UPDATE ON public.refunds
    FOR EACH ROW
    EXECUTE FUNCTION public.handle_refund_status_change();

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own refunds"
    ON public.refunds FOR SELECT
    USING (auth.uid() = user_id);

CREATE POLICY "Users can create refund requests"
    ON public.refunds FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Service role can manage refunds"
    ON public.refunds FOR ALL
    USING (true) WITH CHECK (true);
