-- =============================================
-- SUFashion - revenue_tracking table (Req 14)
-- Daily revenue aggregation driven by triggers
-- Supabase Project: eatekbcknwqxfunyuwel
-- =============================================

CREATE TABLE IF NOT EXISTS public.revenue_tracking (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date          DATE            NOT NULL UNIQUE,
    gross_revenue NUMERIC(12, 2)  NOT NULL DEFAULT 0,
    refund_amount NUMERIC(12, 2)  NOT NULL DEFAULT 0,
    net_revenue   NUMERIC(12, 2)  GENERATED ALWAYS AS (gross_revenue - refund_amount) STORED,
    order_count   INTEGER         NOT NULL DEFAULT 0,
    refund_count  INTEGER         NOT NULL DEFAULT 0,
    updated_at    TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- ── Trigger: order status → 'delivered' adds to gross revenue ────────────────

CREATE OR REPLACE FUNCTION public.track_delivered_revenue()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'delivered' AND OLD.status <> 'delivered' THEN
        INSERT INTO public.revenue_tracking (date, gross_revenue, order_count, updated_at)
        VALUES (DATE(NOW()), NEW.total_price, 1, NOW())
        ON CONFLICT (date) DO UPDATE
        SET gross_revenue = revenue_tracking.gross_revenue + NEW.total_price,
            order_count   = revenue_tracking.order_count + 1,
            updated_at    = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_order_delivered
    AFTER UPDATE ON public.orders
    FOR EACH ROW
    EXECUTE FUNCTION public.track_delivered_revenue();

-- ── Trigger: refund approved deducts from net revenue ────────────────────────

CREATE OR REPLACE FUNCTION public.track_refund_deduction()
RETURNS TRIGGER AS $$
DECLARE
    v_order_date DATE;
BEGIN
    IF NEW.status = 'approved' AND OLD.status <> 'approved' THEN
        SELECT DATE(created_at) INTO v_order_date
          FROM public.orders
         WHERE id = NEW.order_id;

        INSERT INTO public.revenue_tracking (date, refund_amount, refund_count, updated_at)
        VALUES (v_order_date, NEW.amount, 1, NOW())
        ON CONFLICT (date) DO UPDATE
        SET refund_amount = revenue_tracking.refund_amount + NEW.amount,
            refund_count  = revenue_tracking.refund_count + 1,
            updated_at    = NOW();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER on_refund_approved
    AFTER UPDATE ON public.refunds
    FOR EACH ROW
    EXECUTE FUNCTION public.track_refund_deduction();

-- ── Row Level Security ────────────────────────────────────────────────────────

ALTER TABLE public.revenue_tracking ENABLE ROW LEVEL SECURITY;

-- Revenue data is admin-only; service role handles all writes from triggers
CREATE POLICY "Service role can manage revenue_tracking"
    ON public.revenue_tracking FOR ALL
    USING (true) WITH CHECK (true);
