-- =============================================
-- SUFashion - reviews table
-- Supabase Project: eatekbcknwqxfunyuwel
-- Schema source: Supabase OpenAPI (service role)
-- NOT NULL: id, user_id, product_id, rating
-- Reviews require approval before being visible
-- =============================================

CREATE TABLE IF NOT EXISTS public.reviews (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    product_id INTEGER NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
    rating     INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment    TEXT,
    approved   BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Anyone can view approved reviews
CREATE POLICY "Approved reviews are viewable by everyone"
    ON public.reviews
    FOR SELECT
    USING (approved = true);

-- Authenticated users can submit reviews
CREATE POLICY "Authenticated users can add reviews"
    ON public.reviews
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Service role full access (approve / reject reviews)
CREATE POLICY "Service role can manage reviews"
    ON public.reviews
    FOR ALL
    USING (true)
    WITH CHECK (true);
