-- =============================================
-- SUFashion - Req 10/11/12 migration
-- Run this once in the Supabase SQL editor.
--   1. Restrict profiles.role to the four valid roles
-- 2. categories table (product manager add/remove categories)
--   3. products.cost column (sales manager profit/loss reports)
-- =============================================

-- ── 1. Roles (Req 10) ────────────────────────────────────────────────────────
-- customer | admin | sales_manager | product_manager

ALTER TABLE public.profiles DROP CONSTRAINT IF EXISTS profiles_role_check;
ALTER TABLE public.profiles
    ADD CONSTRAINT profiles_role_check
    CHECK (role IN ('customer', 'admin', 'sales_manager', 'product_manager'));

-- Promote test accounts (replace the emails with real signed-up users):
-- UPDATE public.profiles SET role = 'sales_manager'
--   WHERE id = (SELECT id FROM auth.users WHERE email = 'sales@sufashion.test');
-- UPDATE public.profiles SET role = 'product_manager'
--   WHERE id = (SELECT id FROM auth.users WHERE email = 'pm@sufashion.test');

-- ── 2. Categories (Req 12) ───────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.categories (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Categories are viewable by everyone" ON public.categories;
CREATE POLICY "Categories are viewable by everyone"
    ON public.categories
    FOR SELECT
    USING (true);

DROP POLICY IF EXISTS "Service role can manage categories" ON public.categories;
CREATE POLICY "Service role can manage categories"
    ON public.categories
    FOR ALL
    USING (true)
    WITH CHECK (true);

-- Seed from the categories already used on products
INSERT INTO public.categories (name)
SELECT DISTINCT category FROM public.products
WHERE category IS NOT NULL AND category <> ''
ON CONFLICT (name) DO NOTHING;

-- ── 3. Product cost (Req 11 profit/loss) ─────────────────────────────────────
-- Purchase cost per unit. Backfilled at 50% of sale price for existing rows;
-- the sales manager can edit it from the Pricing tab afterwards.

ALTER TABLE public.products ADD COLUMN IF NOT EXISTS cost NUMERIC;
UPDATE public.products SET cost = ROUND(price * 0.5, 2) WHERE cost IS NULL;
